CREATE SCHEMA demo_ds_0;
CREATE TABLE demo_ds_0.t_order_0 (order_id BIGINT NOT NULL AUTO_INCREMENT,user_id INT NOT NULL,PRIMARY KEY(order_id));
CREATE TABLE demo_ds_0.t_order_1 (order_id BIGINT NOT NULL AUTO_INCREMENT,user_id INT NOT NULL,PRIMARY KEY(order_id));
CREATE TABLE demo_ds_0.t_order_2 (order_id BIGINT NOT NULL AUTO_INCREMENT,user_id INT NOT NULL,PRIMARY KEY(order_id));
CREATE TABLE demo_ds_0.t_order_3 (order_id BIGINT NOT NULL AUTO_INCREMENT,user_id INT NOT NULL,PRIMARY KEY(order_id));
CREATE TABLE demo_ds_0.t_order_4 (order_id BIGINT NOT NULL AUTO_INCREMENT,user_id INT NOT NULL,PRIMARY KEY(order_id));
CREATE TABLE demo_ds_0.t_order_5 (order_id BIGINT NOT NULL AUTO_INCREMENT,user_id INT NOT NULL,PRIMARY KEY(order_id));
CREATE TABLE demo_ds_0.t_order_6 (order_id BIGINT NOT NULL AUTO_INCREMENT,user_id INT NOT NULL,PRIMARY KEY(order_id));
CREATE TABLE demo_ds_0.t_order_7 (order_id BIGINT NOT NULL AUTO_INCREMENT,user_id INT NOT NULL,PRIMARY KEY(order_id));
CREATE TABLE demo_ds_0.t_order_8 (order_id BIGINT NOT NULL AUTO_INCREMENT,user_id INT NOT NULL,PRIMARY KEY(order_id));
CREATE TABLE demo_ds_0.t_order_9 (order_id BIGINT NOT NULL AUTO_INCREMENT,user_id INT NOT NULL,PRIMARY KEY(order_id));
CREATE TABLE demo_ds_0.t_order_10 (order_id BIGINT NOT NULL AUTO_INCREMENT,user_id INT NOT NULL,PRIMARY KEY(order_id));
CREATE TABLE demo_ds_0.t_order_11 (order_id BIGINT NOT NULL AUTO_INCREMENT,user_id INT NOT NULL,PRIMARY KEY(order_id));
CREATE TABLE demo_ds_0.t_order_12 (order_id BIGINT NOT NULL AUTO_INCREMENT,user_id INT NOT NULL,PRIMARY KEY(order_id));
CREATE TABLE demo_ds_0.t_order_13 (order_id BIGINT NOT NULL AUTO_INCREMENT,user_id INT NOT NULL,PRIMARY KEY(order_id));
CREATE TABLE demo_ds_0.t_order_14 (order_id BIGINT NOT NULL AUTO_INCREMENT,user_id INT NOT NULL,PRIMARY KEY(order_id));
CREATE TABLE demo_ds_0.t_order_15 (order_id BIGINT NOT NULL AUTO_INCREMENT,user_id INT NOT NULL,PRIMARY KEY(order_id));

insert into demo_ds_0.t_order_0  (user_id) values (1);
insert into demo_ds_0.t_order_1  (user_id) values (2);
insert into demo_ds_0.t_order_2  (user_id) values (3);
insert into demo_ds_0.t_order_3  (user_id) values (4);
insert into demo_ds_0.t_order_4  (user_id) values (5);
insert into demo_ds_0.t_order_5  (user_id) values (6);
insert into demo_ds_0.t_order_6  (user_id) values (7);
insert into demo_ds_0.t_order_7  (user_id) values (8);
insert into demo_ds_0.t_order_8  (user_id) values (9);
insert into demo_ds_0.t_order_9  (user_id) values (10);
insert into demo_ds_0.t_order_10 (user_id) values (11);
insert into demo_ds_0.t_order_11 (user_id) values (12);
insert into demo_ds_0.t_order_12 (user_id) values (13);
insert into demo_ds_0.t_order_13 (user_id) values (14);
insert into demo_ds_0.t_order_14 (user_id) values (15);
insert into demo_ds_0.t_order_15 (user_id) values (16);

CREATE SCHEMA demo_ds_1;
CREATE TABLE demo_ds_1.t_order_0 (order_id BIGINT NOT NULL AUTO_INCREMENT,user_id INT NOT NULL,PRIMARY KEY(order_id));
CREATE TABLE demo_ds_1.t_order_1 (order_id BIGINT NOT NULL AUTO_INCREMENT,user_id INT NOT NULL,PRIMARY KEY(order_id));
CREATE TABLE demo_ds_1.t_order_2 (order_id BIGINT NOT NULL AUTO_INCREMENT,user_id INT NOT NULL,PRIMARY KEY(order_id));
CREATE TABLE demo_ds_1.t_order_3 (order_id BIGINT NOT NULL AUTO_INCREMENT,user_id INT NOT NULL,PRIMARY KEY(order_id));
CREATE TABLE demo_ds_1.t_order_4 (order_id BIGINT NOT NULL AUTO_INCREMENT,user_id INT NOT NULL,PRIMARY KEY(order_id));
CREATE TABLE demo_ds_1.t_order_5 (order_id BIGINT NOT NULL AUTO_INCREMENT,user_id INT NOT NULL,PRIMARY KEY(order_id));
CREATE TABLE demo_ds_1.t_order_6 (order_id BIGINT NOT NULL AUTO_INCREMENT,user_id INT NOT NULL,PRIMARY KEY(order_id));
CREATE TABLE demo_ds_1.t_order_7 (order_id BIGINT NOT NULL AUTO_INCREMENT,user_id INT NOT NULL,PRIMARY KEY(order_id));
CREATE TABLE demo_ds_1.t_order_8 (order_id BIGINT NOT NULL AUTO_INCREMENT,user_id INT NOT NULL,PRIMARY KEY(order_id));
CREATE TABLE demo_ds_1.t_order_9 (order_id BIGINT NOT NULL AUTO_INCREMENT,user_id INT NOT NULL,PRIMARY KEY(order_id));
CREATE TABLE demo_ds_1.t_order_10 (order_id BIGINT NOT NULL AUTO_INCREMENT,user_id INT NOT NULL,PRIMARY KEY(order_id));
CREATE TABLE demo_ds_1.t_order_11 (order_id BIGINT NOT NULL AUTO_INCREMENT,user_id INT NOT NULL,PRIMARY KEY(order_id));
CREATE TABLE demo_ds_1.t_order_12 (order_id BIGINT NOT NULL AUTO_INCREMENT,user_id INT NOT NULL,PRIMARY KEY(order_id));
CREATE TABLE demo_ds_1.t_order_13 (order_id BIGINT NOT NULL AUTO_INCREMENT,user_id INT NOT NULL,PRIMARY KEY(order_id));
CREATE TABLE demo_ds_1.t_order_14 (order_id BIGINT NOT NULL AUTO_INCREMENT,user_id INT NOT NULL,PRIMARY KEY(order_id));
CREATE TABLE demo_ds_1.t_order_15 (order_id BIGINT NOT NULL AUTO_INCREMENT,user_id INT NOT NULL,PRIMARY KEY(order_id));

insert into demo_ds_1.t_order_0  (user_id) values (1);
insert into demo_ds_1.t_order_1  (user_id) values (2);
insert into demo_ds_1.t_order_2  (user_id) values (3);
insert into demo_ds_1.t_order_3  (user_id) values (4);
insert into demo_ds_1.t_order_4  (user_id) values (5);
insert into demo_ds_1.t_order_5  (user_id) values (6);
insert into demo_ds_1.t_order_6  (user_id) values (7);
insert into demo_ds_1.t_order_7  (user_id) values (8);
insert into demo_ds_1.t_order_8  (user_id) values (9);
insert into demo_ds_1.t_order_9  (user_id) values (10);
insert into demo_ds_1.t_order_10 (user_id) values (11);
insert into demo_ds_1.t_order_11 (user_id) values (12);
insert into demo_ds_1.t_order_12 (user_id) values (13);
insert into demo_ds_1.t_order_13 (user_id) values (14);
insert into demo_ds_1.t_order_14 (user_id) values (15);
insert into demo_ds_1.t_order_15 (user_id) values (16);

