datasource:
    types: mysql,postgres
    mysql:
      master:
        driver: com.mysql.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/db
          username: root
          password: root
        slave:
          driver: com.mysql.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3307/db
          username: root
          password:
    postgres:
      master:
        driver: org.postgresql.Driver
        url: jdbc:postgresql://127.0.0.1:5432/test
        username: postgres
        password: 123456
      slave:
        driver: org.postgresql.Driver
        url: jdbc:postgresql://127.0.0.1:5432/test
        username: postgres
        password: 123456